- src/main/java/com/example/team1_be/Team1BEApplication.java
> rename : SpringBootApplication 파일명 변경 Be -> BE

- build.gradle
Size 어노테이션이나 다른 validation 어노테이션에 대한 build.gradle 파일 수정
> build : 검증 기능 추가

- src/main/java/com/example/team1_be/domain/Group/Group.java
- src/test/java/com/example/team1_be/domain/Group/GroupTest.java
> 그룹 엔티티 기능 구현

- src/main/java/com/example/team1_be/domain/Week/Week.java
> feat : week 엔티티 생성

- src/main/java/com/example/team1_be/domain/Group/Group.java
- src/main/java/com/example/team1_be/domain/Group/GroupRepository.java
- src/test/java/com/example/team1_be/domain/Group/GroupRepositoryTest.java
멤버 엔티티 생성을 위해서 유저와 그룹 엔티티의 기본 양식을 작성함
CRUD에서 CR 의 기능만을 구현함
> feat : 그룹 엔티티 기본 양식 작성

- src/main/java/com/example/team1_be/domain/Member/Member.java
- src/main/java/com/example/team1_be/domain/Member/MemberRepository.java
- src/test/java/com/example/team1_be/domain/Member/MemberRepositoryTest.java
멤버의 엔티티를 작성했고, 리포지토리와 테스트 코드를 일부 작성했다.
> feat : 멤버 엔티티 및 리포지토리 작성

- src/main/java/com/example/team1_be/domain/Schedule/Schedule.java
- src/main/java/com/example/team1_be/domain/Schedule/ScheduleRepository.java
- src/test/java/com/example/team1_be/domain/Schedule/ScheduleRepositoryTest.java
> feat : 스케줄 엔티티 기초양식 작성

- src/main/java/com/example/team1_be/domain/Day/Day.java
- src/main/java/com/example/team1_be/domain/Day/DayRepository.java
- src/main/java/com/example/team1_be/domain/Day/Weekday.java
- src/test/java/com/example/team1_be/domain/Day/WeekdayRepositoryTest.java
요일에 대해서 기본 엔티티, 리포지토리, 테스트 코드 작성
도메인들에 대해 양방향 도메인이 필요해 보임.
> feat : 요일 도메인 작성

- src/main/java/com/example/team1_be/domain/Worktime/Worktime.java
- src/main/java/com/example/team1_be/domain/Worktime/WorktimeRepository.java
- src/test/java/com/example/team1_be/domain/Worktime/WorktimeRepositoryTest.java
근무 시간(Worktime)에 대해서 기초 엔티티, 리포지토리, 테스트 코드를 작성함
> feat : 근무 시간 엔티티 작성

- src/main/java/com/example/team1_be/domain/Substitute/SubstitueRepository.java
- src/main/java/com/example/team1_be/domain/Substitute/Substitute.java
- src/main/java/com/example/team1_be/domain/Substitute/SubstituteRepository.java
- src/test/java/com/example/team1_be/domain/Substitute/SubstitueRepositoryTest.java
> feat : 대타 신청

- src/main/resources/data.sql
data.sql에 ,(쉼표) 가 추가되어 입력되지 않던 오류 수정
> fix : 오타 수정

- src/main/resources/data.sql
추가된 kakao_id에 대해서 변경점을 반영함
하지만 변수형을 Long에서 int로 변경해야함
> refactor : 변경된 유저 엔티티 반영

- build.gradle
- src/main/java/com/example/team1_be/domain/Day/DayRepository.java
- src/main/java/com/example/team1_be/domain/Notification/NotificationType.java
- src/main/java/com/example/team1_be/domain/Worktime/WorktimeRepository.java
- src/test/java/com/example/team1_be/BaseTest.java
- src/test/java/com/example/team1_be/domain/Day/DayRepositoryTest.java
- src/test/java/com/example/team1_be/domain/Group/GroupRepositoryTest.java
- src/test/java/com/example/team1_be/domain/Member/MemberRepositoryTest.java
- src/test/java/com/example/team1_be/domain/Schedule/ScheduleRepositoryTest.java
- src/test/java/com/example/team1_be/domain/Week/WeekRepositoryTest.java
- src/test/java/com/example/team1_be/domain/Worktime/WorktimeRepositoryTest.java
- src/test/java/com/example/team1_be/util/WithMockCustomUser.java
- src/test/java/com/example/team1_be/util/WithMockCustomUserSecurityContextFactory.java
스케줄 알고리즘 작성을 위한 더미 데이터 구현
커스터 인증을 제공하여 테스트 환경에서 작동할 수 있도록 제공
> feat : 커스텀 인증 및 더미 데이터 작성 resolves #72

- src/main/java/com/example/team1_be/domain/User/UserService.java
insert 동작에 대해서 Transactional 어노테이션 적용
UserService의 register 메서드에 Transactional 어노테이션 추가
변경 전
```
@Transactional
public void register(User user){
userRepository.save(user);
}
```
변경 후
```
@Transactional
public void register(User user){
userRepository.save(user);
}
```
새로운 기능이 추가되었다면, 그 기능의 사용 방법에 대해서 설명하세요.
모든 서비스는 기본적으로 readOnly 속성을 추가하
read 이외의 기능이 필요한 메서드에 대해서 선택적으로 추가해야 한다.
해당 PR과 관련된 Github Issue가 있다면 여기에 링크를 넣어주세요.
> fix : insert 문에 필요한 Transactional 적용

- src/main/java/com/example/team1_be/domain/Schedule/ScheduleController.java
- src/main/java/com/example/team1_be/domain/Schedule/ScheduleService.java
- src/test/java/com/example/team1_be/BaseTest.java
- src/test/java/com/example/team1_be/domain/Group/controller/GroupControllerTest.java
- src/test/java/com/example/team1_be/domain/Schedule/ScheduleControllerTest.java
- src/test/java/com/example/team1_be/util/WithMockCustomUserSecurityContextFactory.java
- src/test/java/com/example/team1_be/utils/BaseEntityTest.java
스케줄 모집 시작하기 구현
- post - /schedule/worktime 에 대한 컨트롤러 및 서비스 구현
새로운 기능이 추가되었다면, 그 기능의 사용 방법에 대해서 설명하세요.
관련 자료 참고
해당 PR과 관련된 Github Issue가 있다면 여기에 링크를 넣어주세요.
closes #104 
DTO에 적용된 validation 기반으로 테스트 진행
- 스케줄 모집 성공
- 스케줄 모집 실패(startDate 미기입)
- 스케줄 모집 실패(weeklyAmount 미기입)
- 스케줄 모집 실패(weeklyAmount 빈 스케줄)
- 스케줄 모집 성공(weeklyAmount 공백 데이터만 추가)
- 스케줄 모집 실패(WorktimeSchedule 미기입
> feat : 스케줄 모집 시작하기

- src/main/java/com/example/team1_be/domain/Schedule/ScheduleService.java
- src/main/java/com/example/team1_be/domain/User/UserController.java
- src/main/java/com/example/team1_be/utils/ApiUtils.java
- src/main/java/com/example/team1_be/utils/errors/GlobalExceptionHandler.java
- src/main/java/com/example/team1_be/utils/errors/exception/CustomException.java
- src/main/java/com/example/team1_be/utils/security/AuthenticationConfig.java
1. RestControllerAdvice를 적용한 GlobalExceptionHandler 구현
2. 각 비즈니스로직에서 발생하는 에러를 처리하는 CustomException 구현
1. 컨트롤러 동작과정에서 발생하는 DTO 유효성, 비즈니스 로직, 알 수 없는 에러에 대해서 대응가능
2. CustomException으로 비즈니스 로직에서 발생하는 에러처리 가능
1. 인식하지 못한 에러에 대해서는 Exception 에러로 자동 처리됨
2. 비즈니스 로직에서 발생하는 에러는 다음과 같이 처리(orelseThrow 또는 if문에서 적용가능)
```
throw new CustomException("모든 요일에 대한 정보가 없습니다.", HttpStatus.BAD_REQUEST);
```
closes #125 
Schedule Controller에 대해서 Error 코드 검증성공
nested DTO에 대해서 자세한 에러처리가 필요함
모든 컨트롤러에서 발생하는 에러를 다룰 수 있게 됨
> merge : GlobalExceptionHandler 및 CustomException 구현

- src/main/java/com/example/team1_be/domain/Group/GroupController.java
- src/main/java/com/example/team1_be/domain/Group/Invite/DTO/InvitationCheck.java
- src/main/java/com/example/team1_be/domain/Group/Invite/InviteService.java
- src/test/java/com/example/team1_be/domain/Group/GroupControllerTest.java
- src/test/resources/com/example/team1_be/domain/Group/group-invitationCheck1.sql
- src/test/resources/com/example/team1_be/domain/Group/group-invitationCheck2.sql
- src/test/resources/com/example/team1_be/domain/Group/group-invitationCheck3.sql
- src/test/resources/com/example/team1_be/domain/Group/group-invitationCheck4.sql
get 요청으로 전송한 초대장 확인 기능을 구현
- 초대장 확인 요청에 대해서 컨트롤러, 서비스, 응답 DTO, 테스트 코드를 구현
인증된 상태에서 GET : /group/invitaion/information/{초대키} 요청시
그룹에 대한 정보를 제공
closes #130 
- 그룹 초대장 확인 성공
- 그룹 초대장 확인 실패(존재하지 않는 초대장)
- 그룹 초대장 확인 실패(초대장 만료)
- 그룹 초대장 확인 실패(초대장 미갱신)
> feat : 초대장 확인 기능 구현

- src/main/java/com/example/team1_be/domain/Group/DTO/GetMembers.java
- src/main/java/com/example/team1_be/domain/Group/GroupController.java
- src/main/java/com/example/team1_be/domain/Group/GroupService.java
- src/test/java/com/example/team1_be/domain/Group/GroupControllerTest.java
- src/test/resources/com/example/team1_be/domain/Group/group-getMembers1.sql
- src/test/resources/com/example/team1_be/domain/Group/group-getMembers2.sql
그룹원 조회 요청에 대해서 서비스를 구현함
1. 요청시 인증 확인
2. Member에서 사용자 조회하여 유효성 검증
3. 응답 DTO에 그룹과 멤버목록을 전달
GET : /group 요청으로 사용가능
closes #129 
- 그룹원 조회 성공
- 그룹원 조회 실패(멤버 등록안됨)
sql문이 복잡한 문제가 있지만 코드개선을 더하면 개발시간이 촉박해짐
> feat : 그룹원 조회 기능

- src/main/java/com/example/team1_be/domain/Group/DTO/GetInvitation.java
- src/main/java/com/example/team1_be/domain/Group/GroupController.java
- src/main/java/com/example/team1_be/domain/Group/GroupRepository.java
- src/main/java/com/example/team1_be/domain/Group/Invite/Invite.java
- src/main/java/com/example/team1_be/domain/Group/Invite/InviteRepository.java
- src/main/java/com/example/team1_be/domain/Group/Invite/InviteService.java
- src/test/java/com/example/team1_be/domain/Group/GroupControllerTest.java
- src/test/resources/com/example/team1_be/domain/Group/group-getInvitation1.sql
- src/test/resources/com/example/team1_be/domain/Group/group-getInvitation2.sql
- src/test/resources/com/example/team1_be/domain/Group/group-getInvitation3.sql
그룹장의 초대링크 발급 요청에 따른 API 동작 구현
1. 요청시 그룹장 여부 확인
2. 초대장 갱신
1. 그룹장 권한 필요
closes #133 
- 그룹 초대링크 발급 성공
- 그룹 초대링크 발급 실패(그룹 미등록으로 멤버가 아님)
- 그룹 초대링크 발급 실패(그룹장 아님)
repository에 일부 조회 기능들이 추가됨
1. 그룹 기반 초대장 조회
2. 사용자 기반 그룹 조회
API 명세서상의 그룹관련 마지막 이슈
> feat : 초대링크 발급 API 구현

- src/main/java/com/example/team1_be/domain/Schedule/DTO/WeeklyScheduleCheck.java
- src/main/java/com/example/team1_be/domain/Schedule/ScheduleController.java
- src/main/java/com/example/team1_be/domain/Schedule/ScheduleRepository.java
- src/main/java/com/example/team1_be/domain/Schedule/ScheduleService.java
- src/main/java/com/example/team1_be/domain/Week/WeekRepository.java
- src/main/java/com/example/team1_be/domain/Worktime/Worktime.java
- src/main/java/com/example/team1_be/utils/errors/GlobalExceptionHandler.java
- src/test/java/com/example/team1_be/domain/Schedule/ScheduleControllerTest.java
- src/test/java/com/example/team1_be/domain/Week/WeekRepositoryTest.java
- src/test/resources/data.sql
1. 에러 핸들러 응답형태 변경
2. 주별 스케줄 신청 현황 조회 기능 구현
API 에 대해서 컨트롤러, 서비스, 레포지토리 기능을 구현
- weeklyScheduleCheck : API 에 대한 기능
- weeklyScheduleCheck : 컨트롤러와 대응되는 서비스
- findByScheduleIdStartDateAndAndStatus
- findByGroup
API 문서 참조
closes #117 
- 주별 스케줄 신청 현황 조회 실패(매니저-모집중아님)
- 주별 스케줄 신청 현황 조회 실패(잘못된 날짜 양식)
- 주별 스케줄 신청 현황 조회 실패(매니저 시작한 주 신청아님)
- 주별 스케줄 신청 현황 조회 실패(알바생 마감한 주 신청아님)
- 주별 스케줄 신청 현황 조회 성공(매니저)
- 주별 스케줄 신청 현황 조회 성공(알바생)
> feat : 주별 스케줄 신청 현황 조회 구현

- src/main/java/com/example/team1_be/domain/Group/DTO/GetMembers.java
- src/main/java/com/example/team1_be/domain/Group/GroupService.java
: 기획 변경에 따라 그룹원 조회 api 세부 수정
: 그룹원 조회 api에 접속하고 있는 사용자가 누구인지 정보를 제공하는 것으로 기획 변경이 이루어졌습니다. 
: 그룹원 조회 response DTO에 username 필드를 추가하고, 해당 수정 부분에 따라 Group Service 수정을 진행했습니다. 
#147 (그룹원 조회 api 세부 수정)
: Group Controller 테스트에서 기존 존재하는 그룹원 조회 테스트 코드 기반으로 테스트를 실행했고, 결과는 예상대로 passed가 나왔습니다.
> Feat/그룹원 조회 api 세부 수정

- src/main/java/com/example/team1_be/utils/errors/GlobalExceptionHandler.java
- src/main/java/com/example/team1_be/utils/errors/exception/CustomException.java
: GlobalExceptionHandler에서 예외가 발생했을 때, HttpStatus ok로 반환하는 오류 수정 
: CustomException에서 HttpStatus를 가져오기 위해 @Getter 어노테이션을 추가하고,  GlobalExceptionHandler에서 예외 발생 시 알맞은 상태코드를 응답하도록 HttpStatus를 수정하였습니다. 
GlobalExceptionHandler simple bug fix #149
: 기존에 존재하는 실패테스트를 기반으로 컨트롤러 테스트를 진행했고, 통과했습니다. 
> GlobalExceptionHandler simple bug fix 

- src/main/java/com/example/team1_be/domain/Apply/ApplyRepository.java
- src/main/java/com/example/team1_be/domain/Schedule/DTO/GetFixedWeeklySchedule.java
- src/main/java/com/example/team1_be/domain/Schedule/ScheduleController.java
- src/main/java/com/example/team1_be/domain/Schedule/ScheduleService.java
- src/main/java/com/example/team1_be/domain/Week/WeekRepository.java
- src/test/java/com/example/team1_be/domain/Schedule/ScheduleControllerTest.java
- src/test/resources/data.sql
확정스케줄 조회 API 구현
확정스케줄 API에 대해서 컨트롤러, 서비스, 레포지토리, DTO, 테스트를 구현함
/schedule/fix/month/{YYYY-MM}/{멤버 ID} 를 get요청
closes #102 
- 확정 스케줄 조회 성공
- 확정 스케줄 조회 실패(파라미터 에러)
알고리즘에 적용가능한 데이터를 준비하기 어려웠습니다.
그래서 실험샘플이 추가적으로 필요합니다.
> feat : 확정스케줄 API 구현

- src/main/java/com/example/team1_be/domain/Apply/Apply.java
- src/main/java/com/example/team1_be/domain/Schedule/DTO/FixSchedule.java
- src/main/java/com/example/team1_be/domain/Schedule/Recommend/RecommendedWeeklySchedule.java
- src/main/java/com/example/team1_be/domain/Schedule/Recommend/RecommendedWeeklyScheduleRepository.java
- src/main/java/com/example/team1_be/domain/Schedule/Recommend/RecommendedWorktimeApply.java
- src/main/java/com/example/team1_be/domain/Schedule/Recommend/RecommendedWorktimeApplyRepository.java
- src/main/java/com/example/team1_be/domain/Schedule/Recommend/SchduleGenerator.java
- src/main/java/com/example/team1_be/domain/Schedule/ScheduleController.java
- src/main/java/com/example/team1_be/domain/Schedule/ScheduleService.java
- src/main/java/com/example/team1_be/domain/Worktime/Worktime.java
- src/test/java/com/example/team1_be/domain/Schedule/ScheduleControllerTest.java
- src/test/java/com/example/team1_be/domain/Worktime/WorktimeRepositoryTest.java
추천 스케줄 후보 중 하나를 고를때 스케줄 확정 서비스 제공
1. 기존 스케줄 추천 목록 응답에서 저장기능이 추가됨
2. 저장기능이 추가됨에 따라 엔티티들이 새로 추가됨
3. 해당 요청시 기존 추천 목록이 삭제됨
1. 스케줄 추천 목록을 요청 GET : /schedule/recommend/startDate
2. 스케줄 후보 선택 POST : /schedule/fix
closes #163 
- 스케줄 후보 선택 성공 요청만 구현됨
> 스케줄 확정하기 API 구현

- src/main/java/com/example/team1_be/domain/Schedule/DTO/GetFixedWeeklySchedule.java
스케줄 확정 기능의 응답에서 발생한 에러 수정
같은 날짜가 중복되어 출력되는 문제가 발생
기존 사용법과 동일
close #174
기존 테스트 유지
> fix : 스케줄 확정하기 응답 DTO 수정

- src/main/java/com/example/team1_be/domain/Apply/ApplyRepository.java
- src/main/java/com/example/team1_be/domain/Apply/ApplyService.java
- src/main/java/com/example/team1_be/domain/Schedule/DTO/GetApplies.java
- src/main/java/com/example/team1_be/domain/Schedule/ScheduleController.java
- src/main/java/com/example/team1_be/domain/Schedule/Service/ScheduleService.java
- src/test/java/com/example/team1_be/domain/Schedule/GetAppliesTest.java
스케줄 모집 시 기존 스케줄 신청정보 유무를 확인하는 API 구현
- GET: /schedule/application/<startWeekDate=YYYY-MM-DD> 에 대한 API 기능 구현
close #178
현재 성공에 대한 테스트만 구현되어있으며 모든 기능이 구현된 이후 에러에 대한 테스트 코드를 구현할 예정
> feat: 기존 스케줄 신청 현황 조회

- src/main/java/com/example/team1_be/domain/Apply/ApplyRepository.java
- src/main/java/com/example/team1_be/domain/Apply/Service/ApplyReadOnlyService.java
- src/main/java/com/example/team1_be/domain/Apply/Service/ApplyService.java
- src/main/java/com/example/team1_be/domain/Apply/Service/ApplyWriteOnlyService.java
- src/main/java/com/example/team1_be/domain/DetailWorktime/DetailWorktimeRepository.java
- src/main/java/com/example/team1_be/domain/DetailWorktime/Service/DetailWorktimeReadOnlyService.java
- src/main/java/com/example/team1_be/domain/DetailWorktime/Service/DetailWorktimeService.java
- src/main/java/com/example/team1_be/domain/Schedule/DTO/GetApplies.java
- src/main/java/com/example/team1_be/domain/Schedule/DTO/PostApplies.java
- src/main/java/com/example/team1_be/domain/Schedule/DTO/RecruitSchedule.java
- src/main/java/com/example/team1_be/domain/Schedule/ScheduleController.java
- src/main/java/com/example/team1_be/domain/Schedule/Service/ScheduleService.java
- src/main/java/com/example/team1_be/domain/Week/Service/WeekService.java
- src/main/java/com/example/team1_be/domain/Worktime/Service/WorktimeService.java
- src/test/java/com/example/team1_be/domain/Schedule/GetAppliesTest.java
스케줄 제출에 대한 API 구현
이미 제출한 스케줄이 있어도 최근에 신청한 스케줄로 갱신됨
노션에서의 요청양식 참조
apply service의 read write 역할 분리
close #201
- 스케줄 신청/수정 조회 요청 성공
- 스케줄 신청/수정 제출 DTO 확인
- 스케줄 신청/수정 제출 DTO 포함 요청
모든 PR에 대해서 CODEOWNER를 제외한 인원은 MERGE 제한 걸어둠
> 스케줄 신청/수정(제출) API 구현

- src/main/java/com/example/team1_be/domain/User/UserService.java
- src/test/java/com/example/team1_be/domain/Group/GroupControllerTest.java
: 프론트 요청에 맞춰, 그룹이 없는 유저 조회시 groupName을 null 처리한 결과를 응답하도록 수정했습니다.
: 기존에 존재하던 그룹 조회 실패 시 발생하는 상태 코드를 403 -> 200으로 변경하고,  groupName이 null 처리되도록 response를  구성했습니다.
: 그룹원 조회 성공 및 실패 테스트 코드를 실행시켰을때, 모두 통과했으며  response가 요청사항대로 나오는 것을 확인했습니다.
[그룹원 조회 실패(멤버 등록안됨) 테스트 response]
> 그룹이 없는 유저 조회시 groupName null 처리

- src/main/java/com/example/team1_be/domain/Schedule/DTO/FixSchedule.java
- src/main/java/com/example/team1_be/domain/Schedule/DTO/WeeklyScheduleCheck.java
- src/main/java/com/example/team1_be/domain/Schedule/Recommend/WeeklySchedule/RecommendedWeeklySchedule.java
- src/main/java/com/example/team1_be/domain/Schedule/Recommend/WeeklySchedule/RecommendedWeeklyScheduleRepository.java
- src/main/java/com/example/team1_be/domain/Schedule/Recommend/WeeklySchedule/RecommendedWeeklyScheduleService.java
- src/main/java/com/example/team1_be/domain/Schedule/Service/ScheduleService.java
- src/main/java/com/example/team1_be/domain/User/User.java
- src/main/java/com/example/team1_be/domain/Week/Week.java
- src/main/java/com/example/team1_be/utils/errors/GlobalExceptionHandler.java
- src/test/java/com/example/team1_be/domain/Schedule/GetDailyFixedAppliesTest.java
- src/test/java/com/example/team1_be/domain/Schedule/ScheduleControllerTest.java
기존 DTO에서는 특정 주차에 대한 추천 스케줄 조회가 누락되어있던 점에 대한 수정안
- 모든 DTO의 worktime 엔티티 명칭을 카멜케이스로 적용되도록 변경
- 추천목록을 유저기반으로 조회하는 방식에서 특정 주차에 대해 조회하도록 변경
- 추천목록 엔티티에서 User 속성을 Week 속성으로 치환
- 위 사항들에 대한 사이드 이펙트 모두 반영
노션에 참조된 API 기반으로 요청값을 보내면 확인할 수 있고, 테스트 코드에 일부 작성되어 있으니 확인하면됨
close #214 
사이드 이펙트에 대해서 테스트한 결과 변경된사항을 반영해도 의도된 로직대로 수행되었음
> Request DTO 요청 변수 추가에 따른 변경사항 반영

- src/main/resources/application.yml
create 대신 update 옵션으로 기존 DB 보호
- ddl-auto 옵션을 create 에서 udpate로 변경
매번 프로그램 실행히 엔티티 변경사항만 반영됨
closes #220, #58
기존 테스트에 사이드 이펙트 없음
> Hibernate DDL 설정 변경

- build.gradle
- src/main/java/com/example/team1_be/utils/security/AuthenticationConfig.java
- src/main/java/com/example/team1_be/utils/security/XSS/XSSProtectFilter.java
- src/main/java/com/example/team1_be/utils/security/XSS/XSSUtils.java
- src/main/java/com/example/team1_be/utils/security/XSS/XssRequestWrapper.java
- src/test/java/com/example/team1_be/utils/security/AuthenticationConfigTest.java
외부로부터 받는 데이터에서 발생하는 XSS 문제를 해결
- Security Filter Chain 정책 분리
- XSS Protection 헤더 설정
- 타 웹페이지 스크립트 방지
- 문자열 처리용 라이브러리 추가(인코딩)
- XSS 필터 구현
외부로부터의 요청에서 XSS를 검사하게 되었다.
외부로부터 들어오는 모든 데이터는 XSS 검사를 통과하여 특수문자가 &lt 와 같이 인코딩되어 악성 스크립트가 와해된다.
close #222 
악성 스크립트가 담긴 String 데이터를 전달하여 인코딩되는지 확인한 결과 정상적으로 동작함
만약 XSS 필터만을 제거하여도 다른 보안조치에서 세미콜론에 대한 보안이 적용되어 에러로 처리됨을 인지할 것
> XSS Security 구현
